import { EventEmitter } from "node:events";
import { beforeEach, expect, it, vi } from "vitest";
type Handler = (event: { sender: EventEmitter & { id: number } }, value?: unknown) => Promise<unknown>;
const mocks = vi.hoisted(() => ({ handlers: new Map<string, Handler>(), guard: vi.fn(),
  onQuit: undefined as undefined | ((event: { preventDefault: () => void }) => void), quit: vi.fn(),
  status: vi.fn(), test: vi.fn(), cancel: vi.fn(), restore: vi.fn(), sync: vi.fn(), read: vi.fn(() => []), write: vi.fn() }));
vi.mock("electron", () => ({ app: { on: (_name: string, fn: typeof mocks.onQuit) => { mocks.onQuit = fn; }, quit: mocks.quit }, ipcMain: { handle: (name: string, fn: Handler) => mocks.handlers.set(name, fn) } }));
vi.mock("../ipcSenderGuard", () => ({ assertTrustedSender: mocks.guard }));
vi.mock("./antigravityConnection", () => ({ antigravityConnection: mocks }));
vi.mock("../catalog/antigravityCatalog", () => ({ syncAntigravityCatalog: mocks.sync }));
vi.mock("./antigravityEvidenceStore", () => ({ readAntigravityEvidence: mocks.read, writeAntigravityEvidence: mocks.write }));
import { registerAntigravityIpc } from "./antigravityIpc";
beforeEach(() => { vi.resetAllMocks(); mocks.read.mockReturnValue([]); mocks.handlers.clear(); registerAntigravityIpc(); });
const sender = (id: number) => Object.assign(new EventEmitter(), { id });
it("validates test payload before any native invocation", async () => {
  await expect(mocks.handlers.get("nomi:antigravity:test")!({ sender: sender(1) }, { capability: "image", modelId: "auto", command: "bad" })).rejects.toThrow("ANTIGRAVITY_INVALID_TEST");
  expect(mocks.guard).toHaveBeenCalledOnce();
  expect(mocks.test).not.toHaveBeenCalled();
});
it("binds cancellation to the initiating window and waits for process settlement", async () => {
  let finish!: (value: unknown) => void;
  const result = { state: "unverified", models: [], checkedAt: 1, loginCommand: "agy", checks: [] };
  mocks.test.mockImplementation(() => new Promise((resolve) => { finish = resolve; }));
  const owner = { sender: sender(1) };
  const pending = mocks.handlers.get("nomi:antigravity:test")!(owner, { capability: "text", modelId: "auto" });
  await vi.waitFor(() => expect(mocks.test).toHaveBeenCalledOnce());
  await expect(mocks.handlers.get("nomi:antigravity:cancel")!({ sender: sender(2) })).rejects.toThrow("ANTIGRAVITY_OWNER_MISMATCH");
  expect(mocks.cancel).not.toHaveBeenCalled();
  let cancelled = false;
  const cancellation = mocks.handlers.get("nomi:antigravity:cancel")!(owner).then(() => { cancelled = true; });
  await Promise.resolve();
  expect(cancelled).toBe(false);
  finish(result);
  await Promise.all([pending, cancellation]);
  expect(mocks.cancel).toHaveBeenCalledOnce();
  expect(mocks.sync).toHaveBeenCalledWith(result);
  expect(owner.sender.listenerCount("destroyed")).toBe(0);
});
it("waits for native verification cleanup on quit, including repeated quit events, and refuses new tests", async () => {
  let finish!: (value: unknown) => void;
  mocks.test.mockImplementation(() => new Promise((resolve) => { finish = resolve; }));
  const owner = { sender: sender(1) };
  const pending = mocks.handlers.get("nomi:antigravity:test")!(owner, { capability: "image", modelId: "auto" });
  const event = { preventDefault: vi.fn() };
  mocks.onQuit?.(event); mocks.onQuit?.(event);
  expect(event.preventDefault).toHaveBeenCalledTimes(2);
  expect(mocks.cancel).toHaveBeenCalledOnce();
  expect(mocks.quit).not.toHaveBeenCalled();
  await expect(mocks.handlers.get("nomi:antigravity:test")!(owner, { capability: "text", modelId: "auto" })).rejects.toThrow("ANTIGRAVITY_SHUTTING_DOWN");
  finish({ state: "unverified", models: [], checkedAt: 1, loginCommand: "agy", checks: [] });
  await pending;
  await vi.waitFor(() => expect(mocks.quit).toHaveBeenCalledOnce());
});
it("keeps cancellation and new submissions waiting until the finished result is persisted", async () => {
  let finish!: () => void;
  const persisting = new Promise<void>((resolve) => { finish = resolve; });
  const ready = { state: "ready", models: [], checkedAt: 1, loginCommand: "agy", checks: [] };
  mocks.test.mockResolvedValue(ready); mocks.sync.mockReturnValue(persisting);
  const owner = { sender: sender(1) };
  const pending = mocks.handlers.get("nomi:antigravity:test")!(owner, { capability: "text", modelId: "auto" });
  await vi.waitFor(() => expect(mocks.sync).toHaveBeenCalledOnce());
  let settled = false;
  const cancellation = mocks.handlers.get("nomi:antigravity:cancel")!(owner).then((result) => { settled = true; return result; });
  await Promise.resolve(); await Promise.resolve();
  expect(settled).toBe(false);
  await expect(mocks.handlers.get("nomi:antigravity:test")!(owner)).rejects.toThrow("ANTIGRAVITY_TEST_ACTIVE");
  finish();
  await expect(cancellation).resolves.toEqual(ready);
  await expect(pending).resolves.toEqual(ready);
});
it("returns an owned just-finished result when success wins the cancellation IPC race", async () => {
  const ready = { state: "ready", models: [], checkedAt: 1, loginCommand: "agy", checks: [] };
  mocks.test.mockResolvedValue(ready);
  const owner = { sender: sender(1) };
  await mocks.handlers.get("nomi:antigravity:test")!(owner);
  await expect(mocks.handlers.get("nomi:antigravity:cancel")!(owner)).resolves.toEqual(ready);
  await expect(mocks.handlers.get("nomi:antigravity:cancel")!({ sender: sender(2) })).resolves.toBeUndefined();
  expect(mocks.cancel).not.toHaveBeenCalled();
});
it("quit waits for persistence even when native work has already finished", async () => {
  let finish!: () => void;
  const persisting = new Promise<void>((resolve) => { finish = resolve; });
  mocks.test.mockResolvedValue({ state: "ready", models: [], checkedAt: 1, loginCommand: "agy", checks: [] });
  mocks.sync.mockReturnValue(persisting);
  const pending = mocks.handlers.get("nomi:antigravity:test")!({ sender: sender(1) });
  await vi.waitFor(() => expect(mocks.sync).toHaveBeenCalledOnce());
  const event = { preventDefault: vi.fn() };
  mocks.onQuit?.(event);
  await Promise.resolve(); await Promise.resolve(); await Promise.resolve();
  expect(mocks.quit).not.toHaveBeenCalled();
  mocks.onQuit?.(event);
  expect(event.preventDefault).toHaveBeenCalledTimes(2);
  finish(); await pending;
  await vi.waitFor(() => expect(mocks.quit).toHaveBeenCalledOnce());
});
