// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接（audio 分片）。合并出口在 archetypeWireDefaults.generated.ts。
export const ARCHETYPE_WIRE_DEFAULTS_AUDIO: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "nomi-audio": {
    "text_to_audio": {
      "*": {
        "voice": "alloy",
        "speed": 1,
        "model": "gpt-4o-mini-tts"
      }
    },
    "transcribe": {
      "*": {
        "language": "",
        "model": "whisper-1"
      }
    }
  },
  "volcengine-doubao-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  },
  "seed-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  }
};
