// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接（model3d 分片）。合并出口在 archetypeWireDefaults.generated.ts。
export const ARCHETYPE_WIRE_DEFAULTS_MODEL3D: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "hunyuan3d": {
    "text_to_3d": {
      "*": {
        "generateType": "Normal",
        "faceCount": 500000,
        "enablePbr": true
      }
    },
    "image_to_3d": {
      "*": {
        "generateType": "Normal",
        "faceCount": 500000,
        "enablePbr": true
      }
    }
  },
  "hitem3d": {
    "image_to_3d": {
      "*": {
        "requestType": "mesh",
        "resolution": "1536pro",
        "face": 2000000
      }
    }
  },
  "meshy6": {
    "text_to_3d": {
      "*": {
        "artStyle": "realistic",
        "topology": "triangle",
        "targetPolycount": 30000,
        "symmetryMode": "auto",
        "shouldRemesh": true,
        "enablePbr": true
      }
    },
    "image_to_3d": {
      "*": {
        "topology": "triangle",
        "targetPolycount": 30000,
        "symmetryMode": "auto",
        "shouldRemesh": true,
        "shouldTexture": true,
        "enablePbr": true
      }
    }
  }
};
