// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接（image 分片）。合并出口在 archetypeWireDefaults.generated.ts。
export const ARCHETYPE_WIRE_DEFAULTS_IMAGE: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "gpt-image-2": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "model": "gpt-image-2-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "model": "gpt-image-2-image-to-image"
      }
    }
  },
  "seedream": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "model": "seedream/4.5-text-to-image"
      },
      "apimart": {
        "size": "1:1",
        "resolution": "2K",
        "model": "seedream/4.5-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "model": "seedream/4.5-edit"
      },
      "apimart": {
        "size": "1:1",
        "resolution": "2K",
        "model": "seedream/4.5-edit"
      }
    }
  },
  "kie-seedream-5-pro": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "output_format": "png",
        "model": "seedream/5-pro-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "output_format": "png",
        "model": "seedream/5-pro-image-to-image"
      }
    }
  },
  "kie-seedream-5-lite": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "output_format": "png",
        "model": "seedream/5-lite-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "output_format": "png",
        "model": "seedream/5-lite-image-to-image"
      }
    }
  },
  "nano-banana-2": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "output_format": "png"
      },
      "apimart": {
        "size": "auto",
        "resolution": "1K"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "output_format": "png"
      },
      "apimart": {
        "size": "auto",
        "resolution": "1K"
      }
    }
  },
  "nano-banana-2-lite": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "auto"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "auto"
      }
    }
  },
  "nano-banana": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "output_format": "png",
        "model": "google/nano-banana"
      },
      "apimart": {
        "size": "1:1",
        "model": "google/nano-banana"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "output_format": "png",
        "model": "google/nano-banana-edit"
      },
      "apimart": {
        "size": "1:1",
        "model": "google/nano-banana-edit"
      }
    }
  },
  "flux-2-pro": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "resolution": "1K",
        "model": "flux-2/pro-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "resolution": "1K",
        "model": "flux-2/pro-image-to-image"
      }
    }
  },
  "qwen-image-3": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-3.0"
      }
    },
    "image_edit": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-3.0"
      }
    }
  },
  "qwen-image": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-2.0"
      }
    },
    "image_edit": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-2.0"
      }
    }
  },
  "imagen-4": {
    "text_to_image": {
      "*": {
        "size": "16:9"
      }
    }
  },
  "z-image-turbo": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "1K"
      }
    }
  },
  "seedream-5-pro": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "2K"
      }
    },
    "image_edit": {
      "*": {
        "size": "1:1",
        "resolution": "2K"
      }
    }
  },
  "modelscope-image": {
    "text_to_image": {
      "*": {
        "size": "1024x1024"
      }
    }
  },
  "volcengine-seedream": {
    "text_to_image": {
      "*": {
        "size": "2048x2048"
      }
    },
    "image_edit": {
      "*": {
        "size": "2048x2048"
      }
    }
  },
  "volcengine-seedream-5-pro": {
    "text_to_image": {
      "*": {
        "size": "2048x2048",
        "background": "opaque"
      }
    },
    "image_edit": {
      "*": {
        "size": "2048x2048",
        "background": "opaque"
      }
    }
  },
  "dreamina-image": {
    "text_to_image": {
      "*": {
        "ratio": "1:1",
        "resolution_type": "2k",
        "model": "5.0"
      }
    },
    "image_edit": {
      "*": {
        "ratio": "1:1",
        "resolution_type": "2k",
        "model": "5.0"
      }
    }
  },
  "dreamina-upscale": {
    "image_edit": {
      "*": {
        "resolution_type": "2k"
      }
    }
  },
  "rh-seedream-4.5": {
    "text_to_image": {
      "*": {
        "resolution": "2k"
      }
    },
    "image_edit": {
      "*": {
        "resolution": "2k"
      }
    }
  },
  "rh-nano-banana": {
    "text_to_image": {
      "*": {
        "aspectRatio": "1:1"
      }
    },
    "image_edit": {
      "*": {
        "aspectRatio": "1:1"
      }
    }
  },
  "rh-gpt-image-2": {
    "text_to_image": {
      "*": {
        "resolution": "2k",
        "quality": "medium",
        "aspectRatio": "16:9"
      }
    },
    "image_edit": {
      "*": {
        "resolution": "2k",
        "quality": "medium",
        "aspectRatio": "16:9"
      }
    }
  },
  "rh-qwen-image-2.0": {
    "text_to_image": {
      "*": {
        "size": "1024*1024",
        "promptExtend": true
      }
    },
    "image_edit": {
      "*": {
        "size": "1024*1024"
      }
    }
  },
  "agnes-image": {
    "text_to_image": {
      "*": {
        "size": "1024x1024"
      }
    },
    "image_edit": {
      "*": {
        "size": "1024x1024"
      }
    }
  },
  "agnes-image-2.1": {
    "text_to_image": {
      "*": {
        "size": "1K",
        "ratio": "1:1"
      }
    },
    "image_edit": {
      "*": {
        "size": "1K",
        "ratio": "1:1"
      }
    }
  }
};
