// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接：headless/MCP 生成缺参时 runtime 按 (archetypeId, taskKind) 兜底填，既有值优先。
// 表体按 kind 分片（各 *.generated.ts），此处合并 —— 分片是为了不让单文件随档案数顶破 800 行巨壳门岗。
import { ARCHETYPE_WIRE_DEFAULTS_IMAGE } from "./archetypeWireDefaults.image.generated";
import { ARCHETYPE_WIRE_DEFAULTS_VIDEO } from "./archetypeWireDefaults.video.generated";
import { ARCHETYPE_WIRE_DEFAULTS_AUDIO } from "./archetypeWireDefaults.audio.generated";
import { ARCHETYPE_WIRE_DEFAULTS_MODEL3D } from "./archetypeWireDefaults.model3d.generated";

export const ARCHETYPE_WIRE_DEFAULTS: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  ...ARCHETYPE_WIRE_DEFAULTS_IMAGE,
  ...ARCHETYPE_WIRE_DEFAULTS_VIDEO,
  ...ARCHETYPE_WIRE_DEFAULTS_AUDIO,
  ...ARCHETYPE_WIRE_DEFAULTS_MODEL3D,
};

// size 键比例语义桥接（从档案 size 控件选项集 derive）：headless size 别名闸据此判「调用方比例能否落到 size」，
// 不再只按默认值字面形状猜（修 seedance-2.5-apimart t2v 的 size 默认 "adaptive" 被误判像素语义、吞掉调用方比例）。
export const ARCHETYPE_SIZE_RATIO_SEMANTIC: Record<string, Record<string, boolean>> = {
  "seedream": {
    "text_to_image": true,
    "image_edit": true
  },
  "nano-banana-2": {
    "text_to_image": true,
    "image_edit": true
  },
  "nano-banana": {
    "text_to_image": true,
    "image_edit": true
  },
  "qwen-image-3": {
    "text_to_image": true,
    "image_edit": true
  },
  "qwen-image": {
    "text_to_image": true,
    "image_edit": true
  },
  "imagen-4": {
    "text_to_image": true
  },
  "z-image-turbo": {
    "text_to_image": true
  },
  "wan-2.7": {
    "text_to_video": true,
    "image_to_video": true
  },
  "wan-3.0-apimart": {
    "text_to_video": true,
    "image_to_video": true
  },
  "grok-imagine-1.5-video": {
    "text_to_video": true
  },
  "seedance-2-apimart": {
    "text_to_video": true,
    "image_to_video": true
  },
  "seedance-2.5-apimart": {
    "text_to_video": true,
    "image_to_video": true
  },
  "happyhorse-1.1": {
    "text_to_video": true,
    "image_to_video": true
  },
  "seedream-5-pro": {
    "text_to_image": true,
    "image_edit": true
  },
  "omni-flash-ext": {
    "text_to_video": true,
    "image_to_video": true
  }
};
